#!/bin/bash

. /etc/zram-swap-config.conf

createZramSwaps () {
	totalmem=$(free|awk '/^Mem:/{print $2}')
	mem=$((( totalmem * MEM_FACTOR / 100 / SWAP_DEVICES ) * 1024 ))
	drive_size=$((( mem * DRIVE_FACTOR ) /100 ))
	# Check Zram Class created
	if modprobe --verbose --first-time zram 2>&1
	then
		DEV_NUM='0'
		echo zram${DEV_NUM}" "$SWAP_DEVICES
		echo ${COMP_ALG} > /sys/block/zram${DEV_NUM}/comp_algorithm
		echo ${drive_size} > /sys/block/zram${DEV_NUM}/disksize
		echo ${mem} > /sys/block/zram${DEV_NUM}/mem_limit
		mkswap /dev/zram${DEV_NUM}
		swapon -v -p ${SWAP_PRI} /dev/zram${DEV_NUM}
	else
		DEV_NUM=$(cat /sys/class/zram-control/hot_add)
		echo zram${DEV_NUM}" "$SWAP_DEVICES
		echo ${COMP_ALG} > /sys/block/zram${DEV_NUM}/comp_algorithm
		echo ${drive_size} > /sys/block/zram${DEV_NUM}/disksize
		echo ${mem} > /sys/block/zram${DEV_NUM}/mem_limit
		mkswap /dev/zram${DEV_NUM}
		swapon -v -p ${SWAP_PRI} /dev/zram${DEV_NUM}
	fi

	if [ "$SWAP_DEVICES" -gt 1 ];then
		for i in $(seq $((SWAP_DEVICES - 1)))
		do
			DEV_NUM=$(cat /sys/class/zram-control/hot_add)
			echo zram${DEV_NUM}" "$SWAP_DEVICES
			echo ${COMP_ALG} > /sys/block/zram${DEV_NUM}/comp_algorithm
			echo ${drive_size} > /sys/block/zram${DEV_NUM}/disksize
			echo ${mem} > /sys/block/zram${DEV_NUM}/mem_limit
			mkswap /dev/zram${DEV_NUM}
			swapon -v -p ${SWAP_PRI} /dev/zram${DEV_NUM}
		done
	fi
	
	# Enable page-cluster tweak 0 pages=1
	sysctl vm.page-cluster=${PAGE_CLUSTER}
	sysctl vm.swappiness=${SWAPPINESS}
	
}

case "$1" in
	start)
		createZramSwaps		
		;;
	stop)
		if DEVICES=$(grep zram /proc/swaps | awk '{print $1}'); then
			for i in $DEVICES; do
				swapoff $i
				DEV_NUM=$(echo "$i" | tr -dc '0-9')
				echo "$DEV_NUM" > /sys/class/zram-control/hot_remove
				echo "$DEV_NUM"
			done
		fi
		;;
	*)
		echo "Usage: zram-swap-config {start|stop}" >&2
		exit 1
		;;
esac
