#!/usr/bin/env sh

. /etc/zram-swap-config.conf

createZramSwaps () {
	totalmem=$(free|awk '/^Mem:/{print $2}')
	mem=$((( totalmem * MEM_FACTOR / 100 / SWAP_DEVICES ) * 1024 ))
	drive_size=$((( mem * DRIVE_FACTOR ) /100 ))
	# Check Zram Class created
	if [ ! -d "/sys/class/zram-control" ]; then
        	modprobe zram
        	RAM_DEV='0'
		echo ${COMP_ALG} > /sys/block/zram${RAM_DEV}/comp_algorithm
		echo ${drive_size} > /sys/block/zram${RAM_DEV}/disksize
		echo ${mem} > /sys/block/zram${RAM_DEV}/mem_limit
		mkswap /dev/zram${RAM_DEV}
		swapon -p ${SWAP_PRI} /dev/zram${RAM_DEV}
	else
        	RAM_DEV=$(cat /sys/class/zram-control/hot_add)
		echo ${COMP_ALG} > /sys/block/zram${RAM_DEV}/comp_algorithm
		echo ${drive_size} > /sys/block/zram${RAM_DEV}/disksize
		echo ${mem} > /sys/block/zram${RAM_DEV}/mem_limit
		mkswap /dev/zram${RAM_DEV}
		swapon -p ${SWAP_PRI} /dev/zram${RAM_DEV}
	fi

	if [ "$SWAP_DEVICES" -gt 1 ];then
		for i in $(seq $((SWAP_DEVICES - 1))); do
			RAM_DEV=$(cat /sys/class/zram-control/hot_add)
			echo ${COMP_ALG} > /sys/block/zram${RAM_DEV}/comp_algorithm
			echo ${drive_size} > /sys/block/zram${RAM_DEV}/disksize
			echo ${mem} > /sys/block/zram${RAM_DEV}/mem_limit
			mkswap /dev/zram${RAM_DEV}
			swapon -p ${SWAP_PRI} /dev/zram${RAM_DEV}
		done
	fi
	
	# Enable page-cluster tweak 0 pages=1
	sysctl vm.page-cluster=${PAGE_CLUSTER}
	sysctl vm.swappiness=${SWAPPINESS}
	
}

case "$1" in
	start)
		sleep .1
		createZramSwaps		
		nohup /usr/local/bin/zram-swap-config-slb > /dev/null 2>&1 &
		;;
	stop)
		kill $(cat /usr/local/bin/zram-swap-config-slb-pid)
		if DEVICES=$(grep zram /proc/swaps | awk '{print $1}'); then
			for i in $DEVICES; do
				swapoff $i
			done
		fi
		;;
	*)
		echo "Usage: log2ram {start|stop}" >&2
		exit 1
		;;
esac
